# -*- coding: utf-8 -*-
"""Ana Beatriz_Web_Scraping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Lr3kQygWWVR7-_tkjx9oJSZZO2BEuhl
"""

## Atividade Tópicos em estatística compuatacional

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(devtools)
# 
# devtools::install_github("tidyverse/rvest")
# 
# library(rvest)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# url <- "https://stackoverflow.com/questions?sort=votes"
# trading_webpage <- read_html(url)
# 
# cat(substr(as.character(trading_webpage), 1, 2000))
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(rvest)
# 
# url <- "https://stackoverflow.com/questions?sort=votes"
# page <- read_html(url)
# 
# # Pega os títulos
# titles <- page %>%
#   html_nodes(".s-post-summary h3 a") %>%
#   html_text2()
# 
# head(titles, 5)
#

"""### Pegando mais que os títulos e criando o df"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(rvest)
# library(dplyr)
# 
# url <- "https://stackoverflow.com/questions?sort=votes"
# page <- read_html(url)
# 
# posts <- html_nodes(page, ".s-post-summary")
# 
# # Título e link
# titles <- html_node(posts, "h3 a") %>% html_text2()
# links <- html_node(posts, "h3 a") %>% html_attr("href")
# 
# # Estatísticas (score, respostas, visualizações)
# stats <- posts %>%
#   html_nodes(".s-post-summary--stats-item-number") %>%
#   html_text2()
# 
# # Reorganiza em colunas
# stats_matrix <- matrix(stats, ncol = 3, byrow = TRUE)
# 
# df <- data.frame(
#   titulo = titles,
#   link = paste0("https://stackoverflow.com", links),
#   score = stats_matrix[,1],
#   respostas = stats_matrix[,2],
#   views = stats_matrix[,3],
#   stringsAsFactors = FALSE
# )
# 
# head(df, 5)
#

"""Os dados precisaram de ajustes para ficarem mais adequados."""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# 
# summary(df)

"""Extraindo informações

"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(ggplot2)
# 
# # Certficando que os views será lido como númerico
# df2 <- df %>%
#   mutate(
#     views_num = as.numeric(gsub("m", "", gsub("k", "", views))) *
#                 ifelse(grepl("m", views), 1e6,
#                        ifelse(grepl("k", views), 1e3, 1))
#   )
# 
# # Gráfico de barras
# ggplot(df2, aes(x = reorder(titulo, views_num), y = views_num)) +
#   geom_col(fill = "steelblue") +
#   coord_flip() +  # deixa os títulos legíveis
#   labs(
#     x = "Título",
#     y = "Visualizações"  ) +
#   scale_y_continuous(labels = scales::comma)
#

"""O título "How do undo the most recent local commits in git?" em português "Como desfazer os commits locais mais recentes no git" foi oque teve mais vizualização.

Agora comparando a quantidade de respostas com o título.

Assim como no anterior, deixando o quantitaivo de respostas como variável númerica antes da construção do gráfico para que não haja erros no gráfico.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# df2 <- df %>%
#   mutate(
#     respostas_num = as.numeric(gsub("[^0-9]", "", respostas))  # remove textos não numéricos
#   )
# 
# # Gráfico de barras
# ggplot(df2, aes(x = reorder(titulo, respostas_num), y = respostas_num)) +
#   geom_col(fill = "tomato") +
#   coord_flip() +  # deixa os títulos legíveis
#   labs(
#     x = "Título da Pergunta",
#     y = "Número de Respostas"
#   ) +
#   scale_y_continuous(labels = scales::comma)

"""Bem como a de vizualização de respostas para cada tópico tem como lider a que trata de commits no Github.

Investigando quais palavras aparecem mais vezes.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# install.packages("tidytext")
# install.packages("stringr")
# library(tidytext)
# library(stringr)
# 
# # Transformar os títulos em palavras individuais
# words_df <- df %>%
#   select(titulo) %>%
#   unnest_tokens(word, titulo) %>%   # separa cada palavra
#   filter(!word %in% c("the", "is", "do", "how", "what", "and", "in", "of", "to"))  # remover stopwords básicas

# Commented out IPython magic to ensure Python compatibility.
# %%R
# word_count <- words_df %>%
#   count(word, sort = TRUE)
#

"""Pegando as 10 palavras que mais aparecem, o comando sort ordena."""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# top_words <- word_count %>%
#   slice_max(n, n = 10)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# ggplot(top_words, aes(x = reorder(word, n), y = n)) +
#   geom_col(fill = "steelblue") +
#   coord_flip() +
#   labs(
#     x = "Palavra",
#     y = "Frequência",
#     title = ""
#   )
#

"""A maioria das palavras que se repetem são de palavras comuns para qualquer tipo de texto, algumas como git, branch, array, processing denotam melhor o tipo de assunto da página.

Removendo mais palavras básicas.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# words_df <- df %>%
#   select(titulo) %>%
#   unnest_tokens(word, titulo) %>%   # separa cada palavra
#   filter(!word %in% c("the", "is", "do", "how", "what", "and", "in", "of", "to","i","can","an","does","why","a"))  # remover stopwords básicas
# 
# 
#   word_count <- words_df %>%
#   count(word, sort = TRUE)
# 
# 
# 
# top_words <- word_count %>%
#   slice_max(n, n = 10)
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# ggplot(top_words, aes(x = reorder(word, n), y = n)) +
#   geom_col(fill = "steelblue") +
#   coord_flip() +
#   labs(
#     x = "Palavra",
#     y = "Frequência",
#     title = ""
#   )

"""Calculando a correlção das variáveis numericas"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# df_num <- df %>%
#   mutate(
#     score_num = as.numeric(score),
#     respostas_num = as.numeric(gsub("[^0-9]", "", respostas)), # remove qualquer caractere não numérico para que o cálculo seja feito corretamente
#     views_num = as.numeric(gsub("m", "", gsub("k", "", views))) *
#                 ifelse(grepl("m", views), 1e6,
#                        ifelse(grepl("k", views), 1e3, 1))
#   ) %>%
#   select(score_num, respostas_num, views_num)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# cor_matrix <- cor(df_num, use = "complete.obs")
# cor_matrix
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# install.packages("reshape2")
# library(reshape2)
# install.packages("ggcorrplot")
# library(ggcorrplot)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(dplyr)
# 
# df_num <- df %>%
#   mutate(
#     score_num = as.numeric(score),
#     respostas_num = as.numeric(gsub("[^0-9]", "", respostas)),
#     views_num = as.numeric(gsub("m", "", gsub("k", "", views))) *
#                 ifelse(grepl("m", views), 1e6,
#                        ifelse(grepl("k", views), 1e3, 1))
#   ) %>%
#   select(score_num, respostas_num, views_num)
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# library(ggcorrplot)
# 
# cor_matrix <- cor(df_num, use = "complete.obs")
# 
# 
# ggcorrplot(cor_matrix,
#            method = "circle",       # círculos proporcionais à correlação (intuitivo)
#            type = "lower",          # mostrar só a metade inferior
#            lab = TRUE,              # mostrar os valores da correlação para comparação númerica
#            lab_size = 5,
#            colors = c("blue", "white", "red"),  # gradiente de cores
#            ggtheme = theme_minimal())
# 
#

"""A maior correlaço encontrada foi entre o número de vizualizações e o número de respostas para cada "pergunta" do site. Não foram encontradas correlações negativas."""